### ISSUE TITLE
"Disable Ores" not working

### ISSUE THREAD

**Issue by Allomere** [noahc3/oretweaker#1]
I wanted to try out your mod to reduce the ammount of iron generated on the game
At first i used it with all the mods that i allready had installed and noticed that even if i disabled the iron ore generation on your configs iron would still generate, but if i altered the "Custom Ore" config for iron ores it would add that to the vanilla iron generation
I unistalled my other mods to test it on its own because i tought that another mod might be interfering with it, but the issue still occurred :
![image](https://user-images.githubusercontent.com/71918599/103388422-b89b0500-4ae7-11eb-9d52-030da754a6b8.png)
The only problem is with the "Disable Ores" config, the "Custom Ore" works just fine.

**Comment by noahc3** [comment]
Whoops, thanks for reporting. Fixed in v1.0.1.

https://www.curseforge.com/minecraft/mc-mods/oretweaker/files/3153930
