### ISSUE TITLE
[Feature request] - dominant ores

### ISSUE THREAD

**Issue by Gdoui400** [noahc3/oretweaker#12]
I am pretty sure this is impossible but could their be a value we can change to make it so when diamonds spawn iron cant spawn over them.

The value would make the ore with the highest values the most important or it could make it load in last that way it will go over the other blocks or ores that are spawning.

If this is not feasible for you to do in your free time or if its just not achievable then just mark this "Issue" as Closed.

**Comment by noahc3** [comment]
This isn't possible with the vanilla feature generation system as far as I can tell, so it's outside the scope of this mod.
