### ISSUE TITLE
[Large Feature Request!] - Depth mining

### ISSUE THREAD

**Issue by Gdoui400** [noahc3/oretweaker#13]
________________________________________________________________________________________________________________________________________ -Ore density
If we can make custom ores we should be able to make them have different strengths then what vanilla provides

Like making a ore that can only be broken by Netherite
________________________________________________________________________________________________________________________________________
 - Depth mining
Stone at different depths have different strengths and not like how if you mine stone with your fist you don't get the block more like a iron pick and obsidian 

The mod I got the idea for this has been inactive for 4 years now and is call strata
https://www.curseforge.com/minecraft/mc-mods/strata

This mod added 2 "variants" or stone that required more mining power to break

Oretweaker I feel could go big with this added because, theirs plenty of players that feel the mining aspect of the game could, and should be expanded on and more drawn out.

The reason I am not asking a different mod maker to try this is because this mod makes it so you can make custom pockets of ores (or any block!) with Maximum and Minimum heights, and custom textures.

**Comment by Gdoui400** [comment]
another version of the same thing but it was dropped the start of last year
https://www.curseforge.com/minecraft/mc-mods/strata-modified

**Comment by noahc3** [comment]
This is outside of the scope of OreTweaker as it requires more modifications to world gen than just ores. I also don't personally have the time to create or maintain something like this unfortunately.
