### ISSUE TITLE
Read Me file doesn't match config file layout

### ISSUE THREAD

**Issue by TheGamersBrew** [noahc3/oretweaker#19]
current version or Oretweaker config file looks nothing like on the Read Me file here on github.  Please update.

![image](https://user-images.githubusercontent.com/77638191/124342274-61561a00-db88-11eb-9d6d-d69f7f1a87d9.png)

**Comment by noahc3** [comment]
The default configuration file will look like that. The readme gives an example of a fully filled config. You should copy the example and change it as you need.
