### ISSUE TITLE
Q: Does OreTweaker allow me to retroactively add ores to a world that has already been started?

### ISSUE THREAD

**Issue by StygianEmperor** [noahc3/oretweaker#2]
Does OreTweaker allow me to retroactively add ores to a world that has already been started? There are a few mods that rely on their own ores that I'd like to add to a private server a friend and I have been working on for a while now.

**Comment by noahc3** [comment]
It won't add ores to existing chunks (it will to newly generated ones), but this is an interesting concept that I might look into as a separate mod.
