### ISSUE TITLE
I dont have the file name to put the code? Do I add it or was the name changed in the first update?

### ISSUE THREAD

**Issue by Gdoui400** [noahc3/oretweaker#3]

**Comment by Gdoui400** [comment]
I found your reddit post and first off thank you for taking the initiative to make this.

**Comment by Gdoui400** [comment]
but I have been looking for the file you put in the README section and couldn't find it so I started looking for a empty file and had no luck.

**Comment by Gdoui400** [comment]
😔 i try copying and pasting the no vanilla ores command in all of the text files individually...


 it did not work

**Comment by Gdoui400** [comment]
Tried adding the file in the folder it no worky!

**Comment by Gdoui400** [comment]
Still cant find this file-

Configuration
All configuration for this mod is stored in config/oretweaker-common.toml.

**Comment by noahc3** [comment]
The file should be generated after first run, and should be in the config folder alongside fml.toml and forge-client.toml (and maybe forge-common.toml)

![image](https://user-images.githubusercontent.com/6082749/103445678-1856f480-4c3d-11eb-815d-da0788979cc8.png)

**Comment by Gdoui400** [comment]
Thank you so much this helps a lot...

**Comment by Gdoui400** [comment]
Mods incredible!
