### ISSUE TITLE
[Feature request] - Min Vein Level

### ISSUE THREAD

**Issue by Atlntssplayer** [noahc3/oretweaker#4]
First of all thank you for this great addon! I really love it!
I've been experimenting with it since it came out. Spent many hours trying to balance the ore gen for my next playthrough.

There is the setting called "Max Vein Level".

Would / Could you please implement a "Min Vein Level" setting too?

"Min Vein Level" = 40
This would mean that the specific ore would not be generated below this level.
This would give players an even more precise way to set ore distribution.

I have quite a few new ores added by mods in my world and what I would like to achieve is have them kind of layered.
The weaker and more abundant ones would be on top and as you go down you would find the stronger and rarer ores.
The problem is, I use small vein sizes and little spawn rate so it makes finding ores rewarding, but as I go deeper in search of the rare ores I can still find weaker ones and these probably take space from the stronger ones when world generating happens.

So if there would be a "Min Vein Level" setting, I could for example make a world where I don't find iron at diamond level.
If I wanted iron I know that I would only find it closer to the surface and if I want a rare ore I would need to go deeper but then at the deep levels I wouldn't have to worry about finding the more abundant ores from the top.

This would also have a great secondary benefit. If later in the game I want a more common / weaker ore, like iron, I would need to mine close to the surface again because there is none at deep levels. This would give more variety in a way in terms of mining place and level.

Thank you for this great mod!

**Comment by noahc3** [comment]
I originally planned to add a minimum vein level, but I couldn't find any examples of it being used in the game's code so I wasn't sure how to do it. I'll take some time to dig a little deeper, since it was an obvious option pre-1.13, it's probably still there somewhere.

**Comment by Atlntssplayer** [comment]
If it helps, this mod has a minimum setting. It is up do date and open source. It's author has more addons with custom ores on their Github page.
https://github.com/Sinhika/simpletungsten

**Comment by noahc3** [comment]
Got it: 

![image](https://user-images.githubusercontent.com/6082749/103448389-98da1d00-4c5e-11eb-90b9-e1ed73fdd120.png)

Will be included in the next release.

**Comment by noahc3** [comment]
Included in v1.1.0

**Comment by Gdoui400** [comment]
AMAZING WORK!
