### ISSUE TITLE
Diamond ore is disabled by default?

### ISSUE THREAD

**Issue by Atlntssplayer** [noahc3/oretweaker#5]
This is the default oretweaker-common.toml config file:

"Disable Ores" = ["minecraft:diamond_ore"]
"Custom Ore" = []

Diamond is disabled by default. Is this intentional?
Players who install the mod and don't notice this might have a painful time later in the game when they realize there is no diamond to be find.

**Comment by Gdoui400** [comment]
Where is this file I have been looking in the mod file for a few hours new and can't find anything like it.

**Comment by Atlntssplayer** [comment]
The file will be in your minecraft installation's config directory. But it only appears when you already ran the game at least once with the mod installed.

You can make it yourself. Just make a text file with the name oretweaker-common and toml extension and copy these two lines into it and save it in the config folder.
"Disable Ores" = []
"Custom Ore" = []

**Comment by noahc3** [comment]
Oops, did that to figure out Forge's config system and never removed it. I'll get that fixed.

**Comment by Gdoui400** [comment]
Thank you

**Comment by noahc3** [comment]
Fixed in v1.1.0
