### ISSUE TITLE
Amount of ore generated differs very much with the same settings if the same ore is also disabled or not!

### ISSUE THREAD

**Issue by Atlntssplayer** [noahc3/oretweaker#8]
The title basically says it but I'm going to explain in detail and demonstrate with two screenshots so it is clear what I'm thinking of.

Case 1 : Every vanilla ore is disabled, coal included. But in the same config I have custom settings for coal.

"Disable Ores" = ["minecraft:coal_ore", "minecraft:iron_ore", "minecraft:gold_ore", "minecraft:redstone_ore", "minecraft:diamond_ore", "minecraft:lapis_ore", "minecraft:emerald_ore"]

[["Custom Ore"]]
	"Ore Name" = "minecraft:coal_ore"
	"Filler Name" = "minecraft:stone"
	"Max Vein Size" = 3
	"Max Vein Level" = 18
	"Spawn Rate" = 10

Result: according to the custom settings, there will be a small amount of coal in the world.
https://ibb.co/HFkV4Ln - as can be seen on the screenshot, after stone is stripped away there is a small amount of coal. Level and amount seems to be correct according to the settings.

Case 2 : Every vanilla ore is disabled. Coal is not put into the disabled ore list. Custom settings for coal are the same as in Case 1.

"Disable Ores" = ["minecraft:iron_ore", "minecraft:gold_ore", "minecraft:redstone_ore", "minecraft:diamond_ore", "minecraft:lapis_ore", "minecraft:emerald_ore"]

[["Custom Ore"]]
	"Ore Name" = "minecraft:coal_ore"
	"Filler Name" = "minecraft:stone"
	"Max Vein Size" = 3
	"Max Vein Level" = 18
	"Spawn Rate" = 10

Result: There is a lot of coal in big veins even above the max vein levels set in the custom settings.
It seems as if an ore has custom settings but is not disabled at the same time, both the vanilla and custom generation will happen making the custom settings effectively useless.
https://ibb.co/R3NRc5P

If this is normal or intended behavior, please consider putting a comment into the config file so users are warned that they should disable the ores they have custom settings for, or they will have much more generated of it in their world.
Took me a lot of time to find this out.
A 1 line comment about this would make the mod more user friendly.

Thanks!

**Comment by noahc3** [comment]
Yes I'll add a comment about this. When you don't disable Vanilla's ore generation when adding your own, both your custom ore generation and the Vanilla ore generation will occur.

**Comment by noahc3** [comment]
Updated the readme with clarification.
